/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://hv2ebaxmyzcgjbw67wzcr2oxhm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kxplxv7ulffhletvdbsa3fuk3q",
    "aws_cognito_identity_pool_id": "us-east-1:7a6ce26f-d677-4b2b-b2bc-4fee1b21b161",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rQGDtCzgR",
    "aws_user_pools_web_client_id": "2hum1elbkp0mc39csna428s0rr",
    "oauth": {}
};


export default awsmobile;
